"""调整 app 表字段

Revision ID: 094aa2480e13
Revises: cd9599eb9d49
Create Date: 2026-03-28 23:55:26.792832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094aa2480e13'
down_revision = 'cd9599eb9d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
