"""empty message

Revision ID: 1f02f2986e6f
Revises: 9a1b2c3d4e5f
Create Date: 2026-07-10 22:38:52.888357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f02f2986e6f'
down_revision = '9a1b2c3d4e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index('conversation_app_created_by_idx', ['created_by'], unique=False)
        batch_op.create_index('conversation_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index('message_conversation_id_idx', ['conversation_id'], unique=False)
        batch_op.create_index('message_created_by_idx', ['created_by'], unique=False)

    with op.batch_alter_table('message_agent_thought', schema=None) as batch_op:
        batch_op.create_index('message_agent_thought_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('message_agent_thought_conversation_id_idx', ['conversation_id'], unique=False)
        batch_op.create_index('message_agent_thought_message_id_idx', ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_agent_thought', schema=None) as batch_op:
        batch_op.drop_index('message_agent_thought_message_id_idx')
        batch_op.drop_index('message_agent_thought_conversation_id_idx')
        batch_op.drop_index('message_agent_thought_app_id_idx')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('message_created_by_idx')
        batch_op.drop_index('message_conversation_id_idx')

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index('conversation_app_id_idx')
        batch_op.drop_index('conversation_app_created_by_idx')

    # ### end Alembic commands ###
