"""empty message

Revision ID: 5ecb4ced6dae
Revises: 3d7b32cf2319
Create Date: 2026-03-16 23:14:30.917971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ecb4ced6dae'
down_revision = '3d7b32cf2319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
