"""add status to app

Revision ID: cd9599eb9d49
Revises: ecd980d3a0ab
Create Date: 2026-03-16 23:26:44.946746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9599eb9d49'
down_revision = 'ecd980d3a0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        # 同理，给已有表新增 NOT NULL type 字段时，先提供默认值
        batch_op.add_column(
            sa.Column('type', sa.String(length=255), nullable=False, server_default='')
        )
        batch_op.alter_column('type', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
