"""empty message

Revision ID: e043c9d17a2b
Revises: c2f6a7d9b8e1
Create Date: 2026-07-06 23:20:01.645707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e043c9d17a2b'
down_revision = 'c2f6a7d9b8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.create_index('app_account_id_idx', ['account_id'], unique=False)

    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.create_index('app_config_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('app_config_version', schema=None) as batch_op:
        batch_op.create_index('app_config_version_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('app_dataset_join', schema=None) as batch_op:
        batch_op.create_index('app_dataset_join_app_id_dataset_id_idx', ['app_id', 'dataset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_dataset_join', schema=None) as batch_op:
        batch_op.drop_index('app_dataset_join_app_id_dataset_id_idx')

    with op.batch_alter_table('app_config_version', schema=None) as batch_op:
        batch_op.drop_index('app_config_version_app_id_idx')

    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_index('app_config_app_id_idx')

    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_index('app_account_id_idx')

    # ### end Alembic commands ###
