"""empty message

Revision ID: ecd980d3a0ab
Revises: 5ecb4ced6dae
Create Date: 2026-03-16 23:22:13.271827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd980d3a0ab'
down_revision = '5ecb4ced6dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        # 既有表新增 NOT NULL 列，必须先给历史数据一个默认值
        batch_op.add_column(
            sa.Column('status', sa.String(length=255), nullable=False, server_default='')
        )
        # 立刻去掉数据库层面的默认值，保持和 ORM 行为一致
        batch_op.alter_column('status', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
